name: pytorch-BraTS2020-unet-segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pip
  - nibabel
  - matplotlib
  - pandas
  - tensorboard
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - torch
      - torchvision
      - split-folders